### ISSUE TITLE
Unhandled exception. System.ArgumentException: Empty path name is not legal. (Parameter 'path')

### ISSUE THREAD

**Issue by cfoucher** [d8ahazard/HueDream#5]
Just made a fresh build off master for my raspberry pi, and can no longer get it to start up do to the unhandled exception. Rolled back to a previous version for the moment.

```
Unhandled exception. System.ArgumentException: Empty path name is not legal. (Parameter 'path')
  at System.IO.File.ReadAllText(String path)
  at JsonFlatFileDataStore.DataStore.ReadJsonFromFile(String path)
  at JsonFlatFileDataStore.DataStore..ctor(String path, Boolean useLowerCamelCase, String keyProperty, Boolean reloadBeforeGetCollection)
  at HueDream.HueDream.DreamData.GetStore() in /src/HueDream/DreamData.cs:line 19
  at HueDream.HueDream.DreamSync..ctor() in /src/HueDream/DreamSync.cs:line 18
  at HueDream.Startup..ctor(IConfiguration configuration) in /src/Startup.cs:line 11
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
  at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
  at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
  at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
  at Microsoft.Extensions.Hosting.HostBuilder.Build()
  at HueDream.Program.Main(String[] args) in /src/Program.cs:line 7
```

**Comment by d8ahazard** [comment]
Okay, so, there were two issues. 

One was fixed with #4192b5a8e475e877198841e984ea213dd929d00e 

The other may happen yet, it's because I changed the data that gets serialized in and out of config. If you get a JsonReaderException, stop the container, make a backup of your config file, restart the container, and then copy in your hue auth/key/user values, reset mappings, and you're good to go.

Sorry, I won't be making any more config-facing changes that I won't account for in the future. ;)
